version: "3"
services:
    server:
        build:
          context: ../word-flip-app/
          dockerfile: Dockerfile
        image: silkfire/word-flip-app:1.0
        container_name: server
        ports:
            - "3000:3000"
        depends_on:
            - api
        # Specify the URL to the web API
        environment: 
            - API_URL=http://api:8080
    api:
        build:
          context: ../WordFlip.Api/
          dockerfile: Dockerfile-api
        image: silkfire/word-flip-api:1.0
        container_name: api
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        build:
          context: ../WordFlip.Api/
          dockerfile: Dockerfile-db
        image: silkfire/word-flip-api-db:1.0
        container_name: db